### ISSUE TITLE
Reading user input section

### ISSUE THREAD

**Issue by sigzero** [narimiran/nim-basics#13]
This is no longer true:

"VS Code users cannot run this the usual way (using Ctrl+Alt+N) because output window doesn’t allow user inputs. This needs to be run in the terminal."

I just ran the example from vscode and typed my name in the output window and it worked fine.

Hint: c:\Projects\Nim\interaction.exe  [Exec]
What is your name?
Robert
Hello Robert, nice to see you.

**Comment by narimiran** [comment]
Thanks for the report! Last time I used VS Code it wasn't possible. I will correct it shortly.

**Comment by sigzero** [comment]
I think it was changed fairly recently. Thanks! I love the tutorial.
