### ISSUE TITLE
Concurrency and parallelism 

### ISSUE THREAD

**Issue by 98982872** [narimiran/nim-basics#15]
Is there any plans for adding parallelism and concurrency model into the tutorial? This is something that's missing from the official tutorial. Adding topics on async/await, mpsc etc would be greatly helpful to the newcomers such as myself.

**Comment by narimiran** [comment]
I'm guessing you're the same person who asked this on Nim forum, but I'll repeat my answer nonetheless:

These topics go beyond beginners tutorial.
I'll consider them for the "Intermediate Nim" tutorial if/when I begin to write it.
