### ISSUE TITLE
changes in Nim 0.19

### ISSUE THREAD

**Issue by jabbalaci** [narimiran/nim-basics#5]
At `result.nim` you write: "Beware! The default value of strings and sequences is nil, and when we use them as returning types, the result variable needs to be initialized as an empty string ("") or as an empty sequence (@[])."

It changed in Nim 0.19. The default value of strings and sequences is `""` and `@[]`. See https://nim-lang.org/blog/2018/09/26/version-0190-released.html .

BTW, I love this tutorial. Do you plan a continuation?

**Comment by narimiran** [comment]
At the time when you wrote this, there was already new version of the tutorial, updated to use Nim 0.19.0. You probably had cached version.

Please refresh (or re-download pdf) and you should see the new version.

> BTW, I love this tutorial. Do you plan a continuation?

Thank you!  
I would like to make a continuation with more advanced topics, but I cannot promise if/when would that happen.

**Comment by narimiran** [comment]
> I like the style of this tutorial. It's not too long, but still full of useful information with examples and exercises. After reading your tutorial I could write some simple programs in Nim right away.

Thank you for this feedback! Much appreciated! :)
