### ISSUE TITLE
Mention scalable codebases as a reason for strong types?

### ISSUE THREAD

**Issue by richardanaya** [narimiran/nim-basics#7]
In this section:
"Types might seem like a restriction at first, but they allow the Nim compiler to both make your code faster, and make sure you’re not doing something wrong by accident."

Large code bases in particular really are much easier to manage with strong types. Perhaps this is worth mentioning.

I thought this sentence above sounded a little too humble. Strong types are awesome.

**Comment by narimiran** [comment]
> Large code bases in particular really are much easier to manage with strong types. Perhaps this is worth mentioning.

Yes, this can be added as another benefit, agreed.
